### ISSUE TITLE
Question about Get-OSRepoAvailableVersions

### ISSUE THREAD

**Issue by RobertTervin** [OutSystems/OutSystems.SetupTools#91]
When using Get-OSRepoAvailableVersions -Application 'PlatformServer' -MajorVersion '11'
The returned values are:
11.10.0.22422
11.9.1.20359
11.9.0.17011
11.8.2.15398
11.8.1.15035
11.7.3.7036
11.0.607.0
11.0.606.0
11.0.424.0
11.0.211.0
11.0.129.0
11.0.128.0
11.0.108.0
11.0.0.209

However, when view the [Download Search Page](https://www.outsystems.com/Downloads/search/Platform-Server/11/), I noticed there are 3 additional downloads that are not returned when calling Get-OSRepoAvailableVersions
![OS11PlatformDownloads](https://user-images.githubusercontent.com/6026566/108098385-eb25a080-7048-11eb-879f-d4165b3d3bd2.png)

Is there a lag in updates?

Thanks

**Comment by pintonunes** [comment]
Hi @RobertTervin,

Yes, the repos are different and we sync them periodically. That's why our repo will not have all the versions available on the downloads page..  
But you can always download the binaries from downloads and use the -Source switch in the cmdLets.

If you are interested on a particular version we can upload it to the OSRepoAvailableVersions repo. No worries on that.

**Comment by RobertTervin** [comment]
Thanks @pintonunes - that's good to know

We've used the library to upgrade our Dev/UAT environments with minor hitches. but we know h a more consistent upgrade process. Your mileage may vary, right :)

This is a great library!
Bob
